use_frameworks!

platform :ios, '9.0'

target 'YFPageMenu_Example' do
  pod 'YFPageMenu', :path => '../'

  target 'YFPageMenu_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
